on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_VERSION: 1.71.0
  FUTHARK_VERSION: 0.25.2
  FUTHARK_TARGETS: c,multicore
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: clippy, rustfmt

      - name: Install futhark
        uses: luleyleo/install-futhark-action@0.1.0
        with:
          version: ${{ env.FUTHARK_VERSION }}

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets --features ${{ env.FUTHARK_TARGETS }} -- -D warnings

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: rustfmt

      - name: Install futhark
        uses: luleyleo/install-futhark-action@0.1.0
        with:
          version: ${{ env.FUTHARK_VERSION }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --features ${{ env.FUTHARK_TARGETS }} --lib --bins --tests --examples --verbose

  rustfmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain with rustfmt available
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --verbose

  doc:
    name: Doc
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: rustfmt

      - name: Install futhark
        uses: luleyleo/install-futhark-action@0.1.0
        with:
          version: ${{ env.FUTHARK_VERSION }}

      - name: Run cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --verbose

      - name: Run cargo test --doc
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --features ${{ env.FUTHARK_TARGETS }} --doc --verbose